select * from HumanResources.Department
select * from HumanResources.Employee
select * from HumanResources.EmployeeDepartmentHistory
select * from HumanResources.EmployeePayHistory
select * from HumanResources.JobCandidate
select * from HumanResources.Shift
select * from HumanResources.vEmployee
select * from HumanResources.vEmployeeDepartment
select * from HumanResources.vEmployeeDepartmentHistory
select * from HumanResources.vJobCandidate
select * from HumanResources.vJobCandidateEducation
select * from HumanResources.vJobCandidateEmployment
