select * from [Person].[AddressType]
select * from [Person].Address
select * from [Person].BusinessEntity
select * from [Person].BusinessEntityAddress
select * from [Person].BusinessEntityContact
select * from [Person].ContactType
select * from [Person].CountryRegion
select * from [Person].EmailAddress
select * from [Person].Password
select * from [Person].Person
select * from [Person].PersonPhone
select * from [Person].PhoneNumberType
select * from [Person].StateProvince
select * from [Person].vAdditionalContactInfo
select * from [Person].vStateProvinceCountryRegion
